### ISSUE TITLE
Usefulnesses 

### ISSUE THREAD

**Issue by gedw99** [tylermmorton/go-fullstory#1]
The web site for full story is pretty bad at telling you what it does .

it seems to record events of what happened on a users device ? 

No idea if it can catch a crash and send a crash report too ..

**Comment by tylermmorton** [comment]
Hey @gedw99, thanks for your interest. FullStory is meant to run in the browser, thus all of the snippet related code in this package to help you instrument your website. The recording snippet is responsible for [autocapture](https://www.fullstory.com/autocapture/), which records events during a user's browser session, including JavaScript errors and warnings thrown in the console. 

You can also supplement your event data using the API client in this package, by sending events from your backend services and tying them to user sessions via a FullStory Session ID. These events are also indexed in the same way as browser events.

Within (FullStory the App)[app.fullstory.com] you can use these recorded events to watch back a session via [Session Replay](https://www.fullstory.com/session-replay/), or construct different types analyses (called DX objects) such as metrics, funnel analysis, page heatmaps, etc. 

There's plenty more to it, and I'm happy to answer any questions you might have. This package is still a WIP and I plan to push more improvements to the code and documentation to hopefully provide some more clarity, but hopefully this helps for now!

Cheers 😁

**Comment by gedw99** [comment]
Ok that clears a few things up and makes sense..

no crash reports. So need sentry too then ..

I tend to build systems with the backend and browser code using identical code that is all wasm.

It’s all the logic, validation and gui.
Data store calls only occur on server of course via host layer. 

so renders server side in phase 1 and then Client Side takes over in phase 2.

this is so Time to Interaction is lowest possible amount.

so looks like your system will work for me I think ..
 Will close this. Feel free to open if you need more info etc
